# Generated by Django 2.2.7 on 2020-01-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='email',
            field=models.CharField(default='iuii', max_length=40),
            preserve_default=False,
        ),
    ]
