# Generated by Django 2.2.7 on 2020-01-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_scholarshipapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('Birth_certificate', models.ImageField(blank=True, upload_to='profile_pics')),
                ('National_id', models.ImageField(blank=True, upload_to='profile_pics')),
            ],
        ),
    ]
