# Generated by Django 2.2.7 on 2020-01-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_scholarshipapplication_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolinformation',
            old_name='email',
            new_name='Reasons_to_be_sponsored',
        ),
        migrations.RenameField(
            model_name='schoolinformation',
            old_name='Birth_certificate',
            new_name='Recomendation_letter',
        ),
        migrations.RenameField(
            model_name='schoolinformation',
            old_name='phone',
            new_name='academic_level',
        ),
        migrations.RemoveField(
            model_name='schoolinformation',
            name='National_id',
        ),
        migrations.AddField(
            model_name='schoolinformation',
            name='expected_year_of_completion',
            field=models.CharField(default='ee', max_length=40),
            preserve_default=False,
        ),
    ]
