# Generated by Django 2.2.7 on 2020-01-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0003_schoolinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='Birth_certificate',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='National_id',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
