# Generated by Django 2.2.7 on 2020-01-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0003_auto_20200115_0729'),
    ]

    operations = [
        migrations.CreateModel(
            name='JustInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reasons_to_be_sponsored', models.CharField(max_length=40)),
                ('Recomendation_letter', models.ImageField(blank=True, upload_to='profile_pics')),
            ],
        ),
        migrations.RemoveField(
            model_name='schoolinformation',
            name='Reasons_to_be_sponsored',
        ),
        migrations.RemoveField(
            model_name='schoolinformation',
            name='Recomendation_letter',
        ),
    ]
