# Generated by Django 2.2.7 on 2020-01-14 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0004_auto_20200114_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
