# Generated by Django 2.2.7 on 2020-01-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0004_auto_20200115_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justinformation',
            name='Reasons_to_be_sponsored',
            field=models.TextField(max_length=40),
        ),
    ]
