# Generated by Django 2.2.7 on 2020-01-14 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0005_scholarshipapplication_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='email',
            field=models.Field(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
