# Generated by Django 2.2.7 on 2020-01-14 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0010_scholarshipapplication_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='email',
        ),
    ]
